[tool.poetry]
name = "tyempo"
version = "0.1.0"
description = "A weather information provider for Notion dashboards"
authors = ["Cristobal Contreras <crisconru@gmail.com>, Jose Rivera <josemrivera@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
fastapi = "^0.63.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
